function [x]=Roots_of_Jacobi_Polynomial(a,b,n)
% find roots of Jacobi Polynomial degree of N
syms y 
J = ((-1)^n*gamma(b+1))/(gamma(n+b+1))*...
    ...
    ...
    diff((y^(n+b)*((1-y)^(n+a))),n)/...
    ...
    ...
    (y^b*((1-y)^a));
x=sort(double(vpa(solve(J))));





    
